name: deploy-fastapi
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync code to C:\apps\py (mirror)
        shell: powershell
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force
          $src = "$env:GITHUB_WORKSPACE"
          $dst = "C:\apps\py"
          robocopy $src $dst /MIR /XD .git .github venv /XF .env py-out.log py-err.log /NDL /NFL
          if ($LASTEXITCODE -ge 8) { exit $LASTEXITCODE } else { exit 0 }

      - name: Write .env from secret
        shell: powershell
        run: |
          $envPath = "C:\apps\py\.env"
          @'
          ${{ secrets.FASTAPI_ENV_FILE }}
          '@ | Set-Content -Path $envPath

      - name: Recreate venv
        shell: powershell
        run: |
          Remove-Item -Recurse -Force C:\apps\py\venv -ErrorAction SilentlyContinue
          python -m venv C:\apps\py\venv
          C:\apps\py\venv\Scripts\python.exe -m pip install --upgrade pip
          C:\apps\py\venv\Scripts\python.exe -m pip install -r C:\apps\py\requirements.txt

      - name: Restart py-app (NSSM)
        shell: powershell
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force
          C:\nssm\nssm.exe restart py-app
